title = "test"
description = "Delete stuff"
maintainer = "nope1"

[[block]]
friendly_name = "The Sunset Bar - DVC"
world_id = "wrld_44f4a344-4489-4e11-a54a-86971f16f0e6"
game_objects = [
    { name = "ButtonVRCGroups", parent = { name = "Buttons" } }, 
    { name = "Security Barrier", parent = { name = "Barriers" } },
	{ name = "Barriers" },
	{ name = "KillFrenzy" },
	{ name = "Trampoline", parent = { name = "KillFrenzy" } },
	{ name = "TrampolineScript", parent = { name = "Trampoline" } },
	{ name = "WallColliders", parent = { name = "Trampoline" } },
	{ name = "TrampolineScript", parent = { name = "WallColliders" } },
	{ name = "WallCollider", parent = { name = "WallColliders" } },
	{ name = "WallCollider (1)", parent = { name = "WallColliders" } },
	{ name = "WallCollider (2)", parent = { name = "WallColliders" } },
	{ name = "WallCollider (3)", parent = { name = "WallColliders" } },
	{ name = "WallCollider (4)", parent = { name = "WallColliders" } },
	{ name = "WallCollider (5)", parent = { name = "WallColliders" } },
	{ name = "WallCollider (6)", parent = { name = "WallColliders" } },
	{ name = "WallCollider (7)", parent = { name = "WallColliders" } },
	{ name = "Logging", parent = { name = "Udon Scripts"} },
	{ name = "Warp To Jail", parent = { name = "Interactivity"} },
	{ name = "RineyTech Downloaders", parent = { name = "Udon Scripts"} },
	]

[[block]]
friendly_name = "VirtualFurence Furry Convention Hotel Estrel Berlin"
world_id = "wrld_b155ff30-0bbf-486c-afc5-e7a05145387b"
# CEBoard is toggled dynamically based on CE support, so let's disable everything under it and think of a better system later
game_objects = [{ name = "Canvas", parent = { name = "CEBoard" } },
]


[[block]]
friendly_name = "Furry Hideout"
world_id = "wrld_4b341546-65ff-4607-9d38-5b7f8f405132"
game_objects = [
    { name = "Canvas (3)", position = { x = -38.71497, y = 43.23, z = -10.41 }}
]

[[block]]
friendly_name = "It's a big room"
world_id = "wrld_0314ed62-301e-4798-94ba-9c431d6abd51"
game_objects = [
	{ name = "Pool Parlor Table"}
	]
